bin: Minimal fixes in setfacl-recursive

diff --git a/bin/setfacl-recursive b/bin/setfacl-recursive
--- a/bin/setfacl-recursive
+++ b/bin/setfacl-recursive
@@ -1,6 +1,8 @@
 #!/bin/bash
 
-tmp="/tmp/setfacl-recursive-$USER"
+set -eufo pipefail
+
+TEMP_FILE="$(mktemp -t 'setfacl-recursive.XXXXXX')"
 
 if [ $# -eq 0 ]; then
     echo 'Missing parameter: path'
@@ -8,27 +10,25 @@ if [ $# -eq 0 ]; then
 fi
 
 if [ ! -e "$1" ]; then
-    echo 'Path not found'
+    echo "Path not found: $1"
     exit 1
 fi
 
-function quit() {
-    if [ -e "$tmp" ]; then
-        rm "$tmp"
-    fi
+trap teardown EXIT
+
+function teardown() {
+    rm -f "$TEMP_FILE"
 }
 
 
 echo -n 'Get base-rights... '
-getfacl "$1" | grep -v '^#' > "$tmp" || quit $?
+getfacl "$1" | grep -v '^#' > "$TEMP_FILE"
 echo 'Ok'
 
 echo -n 'Reset rights recursive... '
-setfacl -Rb "$1" || quit $?
+setfacl -Rb "$1"
 echo 'Ok'
 
 echo -n 'Set base right recursive... '
-setfacl -RM "$tmp" "$1" || cat "$tmp"; quit $?
+setfacl -RM "$TEMP_FILE" "$1" || { cat "$TEMP_FILE"; exit 1; }
 echo 'Ok'
-
-quit 0
